# Generated by Django 3.0.5 on 2020-04-21 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_officialidentity'),
        ('contracts', '0006_auto_20200421_0907'),
    ]

    operations = [
    ]
