# Generated by Django 3.0.5 on 2020-04-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contractStatus',
            field=models.TextField(default='open'),
            preserve_default=False,
        ),
    ]
