# Generated by Django 3.0.5 on 2020-04-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_minimalblock_minimalchain'),
    ]

    operations = [
        migrations.AddField(
            model_name='minimalchain',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
